version: 2.1

jobs:
  build:
    working_directory: ~/scalacheck-examples
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project/Dependencies.scala" }}{{ checksum "project/plugins.sbt" }}-test2
            - v1-dependencies-
      - run: "sbt update"
      - run: "sbt 'scalafix --version'"
      - save_cache:
          key: v1-dependencies-{{ checksum "project/Dependencies.scala" }}{{ checksum "project/plugins.sbt" }}-test2
          paths:
            - ~/.iv2/cache/
            - ~/.sbt/
            - ~/.coursier/cache/
            - ~/.m2/
      - run: "sbt compile"
      - run: "sbt test:compile"
      - run: "sbt scalafmtSbtCheck"
      - run: "sbt scalafmtCheck"
      - run: "sbt test:scalafmtCheck"
      - run: "sbt 'scalafix --check'"
      - run: "sbt 'test:scalafix --check'"
      - run: "sbt dependencyUpdatesFailBuild"
      - run: "sbt test"
      - run: "sbt test:scalastyle"
      - run: "sbt scapegoat"
      - run: "sbt -Dsonar.login=$SONAR_LOGIN sonarScan"